# .streamlit/secrets.toml

[connections.snowflake]
account = "PBXNOUY.GF48427"
user = "bosedipanjan"
password = "10thNovember@1979"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
